/**
 * Copyright 2008 Pavel Syrtsov
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations
 * under the License.
 */

package com.syrtsov.ddao;

import com.syrtsov.ddao.ops.InsertAndGetGeneratedKeySqlOperation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation InsertAndGetId allows to attach insert statement to ddao method.
 * This Insert statement expected to have autogenerated integer field
 * (like mysql autoincrement) in it that will get returned in result set.
 * If method return type is int it will return generated value.
 * <p/>
 * Created by: Pavel Syrtsov
 * Date: Apr 1, 2007
 * Time: 11:58:13 PM
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
@SqlAnnotation(InsertAndGetGeneratedKeySqlOperation.class)
public @interface InsertAndGetGeneratedKey {
    String value();
}